import type { AppLanguage } from "../types";
const copies = {
  "zh-TW": { organize: "整理到…", finish: "完成整理（保留於卡片庫）", title: "整理這張卡片", description: "加入分類、白板或看板後，卡片會離開隻言片語；內容與標籤仍保留於卡片庫。", kind: "整理方式", topic: "歸入分類", board: "加入白板", kanban: "加入看板", target: "目的地", list: "看板列表", choose: "請選擇", empty: "目前沒有可選目的地，請先建立分類、白板或看板。", apply: "完成整理", cancel: "取消", failed: "整理失敗，卡片仍保留。請重試。" },
  "zh-CN": { organize: "整理到…", finish: "完成整理（保留在卡片库）", title: "整理这张卡片", description: "加入分类、白板或看板后，卡片会离开只言片语；内容与标签仍保留在卡片库。", kind: "整理方式", topic: "归入分类", board: "加入白板", kanban: "加入看板", target: "目的地", list: "看板列表", choose: "请选择", empty: "目前没有可选目的地，请先建立分类、白板或看板。", apply: "完成整理", cancel: "取消", failed: "整理失败，卡片仍保留。请重试。" },
  en: { organize: "Organize into…", finish: "Finish organizing (keep in Library)", title: "Organize this card", description: "Filing this card in a topic, whiteboard or kanban removes it from capture. Its content and tags stay in the Library.", kind: "Organize by", topic: "File in a topic", board: "Add to whiteboard", kanban: "Add to kanban", target: "Destination", list: "Kanban list", choose: "Choose", empty: "No destinations yet. Create a topic, whiteboard or kanban first.", apply: "Organize card", cancel: "Cancel", failed: "Could not organize. Your card is safe. Please retry." },
  ja: { organize: "整理先を選択…", finish: "整理を完了（ライブラリに保存）", title: "カードを整理", description: "分類・ボード・カンバンに追加すると未整理一覧から移動します。内容とタグはライブラリに残ります。", kind: "整理方法", topic: "分類に追加", board: "ボードに追加", kanban: "カンバンに追加", target: "追加先", list: "カンバンリスト", choose: "選択してください", empty: "先に分類・ボード・カンバンを作成してください。", apply: "整理を完了", cancel: "キャンセル", failed: "整理できませんでした。カードは保持されています。" },
  ko: { organize: "정리 위치…", finish: "정리 완료 (라이브러리에 보관)", title: "카드 정리", description: "분류, 보드 또는 칸반에 추가하면 미정리 목록에서 사라집니다. 내용과 태그는 라이브러리에 유지됩니다.", kind: "정리 방법", topic: "분류에 추가", board: "보드에 추가", kanban: "칸반에 추가", target: "대상", list: "칸반 목록", choose: "선택하세요", empty: "먼저 분류, 보드 또는 칸반을 만드세요.", apply: "정리 완료", cancel: "취소", failed: "정리하지 못했습니다. 카드는 유지됩니다. 다시 시도하세요." },
} satisfies Record<AppLanguage, Record<string, string>>;
export function getFleetingCopy(language: AppLanguage) { return copies[language]; }
