import type { AppLanguage } from "../types";

const copies = {
  "zh-TW": { organizer: "知識架構", allCards: "所有卡片", unassigned: "未分類", areas: "領域", area: "領域", topic: "主題", addArea: "新增領域", addTopic: "新增主題", rename: "重新命名", remove: "移除", confirmRemove: (name: string) => `移除主題「${name}」？卡片不會刪除，只會回到未分類。`, confirmRemoveArea: (name: string) => `移除領域「${name}」？底下的主題與卡片會保留，主題將移到獨立主題。`, areaPlaceholder: "領域名稱", topicPlaceholder: "主題名稱", save: "儲存", cancel: "取消", chooseTopic: "卡片主題", noTopic: "未分類", dropHint: "把卡片拖到這裡分類", emptyArea: "尚未建立主題", topicsCount: (count: number) => `${count} 個主題`, cardsCount: (count: number) => `${count} 張`, orphanTopics: "獨立主題", loadMore: (count: number) => `再顯示 ${count} 張卡片` },
  "zh-CN": { organizer: "知识结构", allCards: "所有卡片", unassigned: "未分类", areas: "领域", area: "领域", topic: "主题", addArea: "新增领域", addTopic: "新增主题", rename: "重命名", remove: "移除", confirmRemove: (name: string) => `移除主题“${name}”？卡片不会删除，只会回到未分类。`, confirmRemoveArea: (name: string) => `移除领域“${name}”？主题和卡片会保留，主题将移到独立主题。`, areaPlaceholder: "领域名称", topicPlaceholder: "主题名称", save: "保存", cancel: "取消", chooseTopic: "卡片主题", noTopic: "未分类", dropHint: "将卡片拖到这里分类", emptyArea: "尚未建立主题", topicsCount: (count: number) => `${count} 个主题`, cardsCount: (count: number) => `${count} 张`, orphanTopics: "独立主题", loadMore: (count: number) => `再显示 ${count} 张卡片` },
  en: { organizer: "Knowledge structure", allCards: "All cards", unassigned: "Unassigned", areas: "Areas", area: "Area", topic: "Topic", addArea: "Add area", addTopic: "Add topic", rename: "Rename", remove: "Remove", confirmRemove: (name: string) => `Remove topic “${name}”? Cards will not be deleted; they return to Unassigned.`, confirmRemoveArea: (name: string) => `Remove area “${name}”? Its topics and cards stay; topics become independent.`, areaPlaceholder: "Area name", topicPlaceholder: "Topic name", save: "Save", cancel: "Cancel", chooseTopic: "Card topic", noTopic: "Unassigned", dropHint: "Drop a card here to organize it", emptyArea: "No topics yet", topicsCount: (count: number) => `${count} ${count === 1 ? "topic" : "topics"}`, cardsCount: (count: number) => `${count} ${count === 1 ? "card" : "cards"}`, orphanTopics: "Independent topics", loadMore: (count: number) => `Show ${count} more cards` },
  ja: { organizer: "知識の構造", allCards: "すべてのカード", unassigned: "未分類", areas: "領域", area: "領域", topic: "テーマ", addArea: "領域を追加", addTopic: "テーマを追加", rename: "名前を変更", remove: "削除", confirmRemove: (name: string) => `テーマ「${name}」を削除しますか？カードは削除されず、未分類へ戻ります。`, confirmRemoveArea: (name: string) => `領域「${name}」を削除しますか？テーマとカードは残り、テーマは独立テーマへ移ります。`, areaPlaceholder: "領域名", topicPlaceholder: "テーマ名", save: "保存", cancel: "キャンセル", chooseTopic: "カードのテーマ", noTopic: "未分類", dropHint: "カードをここへドロップして整理", emptyArea: "テーマはまだありません", topicsCount: (count: number) => `${count}テーマ`, cardsCount: (count: number) => `${count}枚`, orphanTopics: "独立テーマ", loadMore: (count: number) => `カードをさらに${count}枚表示` },
  ko: { organizer: "지식 구조", allCards: "모든 카드", unassigned: "미분류", areas: "영역", area: "영역", topic: "주제", addArea: "영역 추가", addTopic: "주제 추가", rename: "이름 변경", remove: "제거", confirmRemove: (name: string) => `주제 ‘${name}’을 제거할까요? 카드는 삭제되지 않고 미분류로 돌아갑니다.`, confirmRemoveArea: (name: string) => `영역 ‘${name}’을 제거할까요? 주제와 카드는 유지되고 주제는 독립 항목으로 이동합니다.`, areaPlaceholder: "영역 이름", topicPlaceholder: "주제 이름", save: "저장", cancel: "취소", chooseTopic: "카드 주제", noTopic: "미분류", dropHint: "카드를 여기에 놓아 분류", emptyArea: "아직 주제가 없습니다", topicsCount: (count: number) => `주제 ${count}개`, cardsCount: (count: number) => `카드 ${count}개`, orphanTopics: "독립 주제", loadMore: (count: number) => `카드 ${count}개 더 보기` },
} as const;

export function getKnowledgeCopy(language: AppLanguage) {
  return copies[language] || copies.en;
}
