import type { AppLanguage, McpAccessMode } from "../types";

const copy = {
  "zh-TW": {
    eyebrow: "外部整合", title: "讓 Codex、Claude Code 控制澄境", summary: "本機 MCP・預設關閉", description: "開啟後，支援 MCP 的工具可以搜尋、讀取與（依你選擇）修改筆記、白板、看板、神經元和待辦。連線只在這台電腦上，不會公開到網路。", enabled: "啟用本機 MCP", enabledHint: "澄境執行時才接受連線", endpoint: "本機連線位址", running: "已可連線", stopped: "未啟用", failed: "無法啟動", access: "存取層級", recommended: "建議", modes: { "read-only": ["唯讀", "只能搜尋與讀取，永遠不修改"], ask: ["每次確認", "每次寫入前由澄境詢問你"], allow: ["允許寫入", "持有權杖的工具可直接修改"] } as Record<McpAccessMode, [string, string]>, allowConfirm: "「允許寫入」不會逐次詢問。只有在你信任已連接的工具、也妥善保管權杖時才建議使用。確定要開啟嗎？", safety: "永久刪除沒有開放給 MCP；外部寫入也會成為一筆可復原的操作。", setup: "連接你的工具", setupHint: "按一下複製完整設定，再貼到對應工具。權杖已包含在內，請不要分享。", copyCodex: "複製 Codex 設定", copyClaude: "複製 Claude Code 指令", copied: "已複製，可以直接貼上。", rotate: "更換連線權杖", rotateConfirm: "更換後，先前貼到 Codex 或 Claude Code 的設定會立即失效，需要重新複製。要繼續嗎？", tokenChanged: "連線權杖已更換，請重新複製工具設定。", recent: "最近的 MCP 操作", noRecent: "尚無操作紀錄", outcomes: { success: "完成", denied: "已拒絕", error: "失敗" }, port: "連接埠", applyPort: "套用", advanced: "連線進階設定",
  },
  "zh-CN": {
    eyebrow: "外部集成", title: "让 Codex、Claude Code 控制澄境", summary: "本机 MCP・默认关闭", description: "开启后，支持 MCP 的工具可以搜索、读取及（按你的选择）修改笔记、白板、看板、神经元和待办。连接只存在于这台电脑，不会公开到网络。", enabled: "启用本机 MCP", enabledHint: "仅在澄境运行时接受连接", endpoint: "本机连接地址", running: "可连接", stopped: "未启用", failed: "无法启动", access: "访问级别", recommended: "推荐", modes: { "read-only": ["只读", "只能搜索和读取，永不修改"], ask: ["每次确认", "每次写入前由澄境询问你"], allow: ["允许写入", "持有令牌的工具可以直接修改"] } as Record<McpAccessMode, [string, string]>, allowConfirm: "“允许写入”不会逐次询问。仅当你信任已连接的工具并妥善保管令牌时使用。确定开启吗？", safety: "MCP 不提供永久删除；外部写入也会成为一项可撤销操作。", setup: "连接你的工具", setupHint: "点击复制完整设置，再粘贴到对应工具。令牌已包含在内，请勿分享。", copyCodex: "复制 Codex 设置", copyClaude: "复制 Claude Code 命令", copied: "已复制，可以直接粘贴。", rotate: "更换连接令牌", rotateConfirm: "更换后，先前粘贴到 Codex 或 Claude Code 的设置会立即失效，需要重新复制。是否继续？", tokenChanged: "连接令牌已更换，请重新复制工具设置。", recent: "最近的 MCP 操作", noRecent: "暂无操作记录", outcomes: { success: "完成", denied: "已拒绝", error: "失败" }, port: "端口", applyPort: "应用", advanced: "连接高级设置",
  },
  en: {
    eyebrow: "EXTERNAL INTEGRATIONS", title: "Let Codex and Claude Code work with ChengJing", summary: "Local MCP · Off by default", description: "MCP-compatible tools can search, read, and—at the access level you choose—change notes, whiteboards, kanban boards, neurons, and tasks. The connection stays on this computer and is never exposed to the internet.", enabled: "Enable local MCP", enabledHint: "Connections work only while ChengJing is running", endpoint: "Local endpoint", running: "Ready", stopped: "Off", failed: "Could not start", access: "Access level", recommended: "Recommended", modes: { "read-only": ["Read only", "Search and read; never change data"], ask: ["Ask every time", "ChengJing confirms every write with you"], allow: ["Allow writes", "Tools holding the token can change data directly"] } as Record<McpAccessMode, [string, string]>, allowConfirm: "Allow writes does not ask for each change. Use it only when you trust the connected tool and have protected the token. Enable it?", safety: "Permanent deletion is not exposed through MCP. External writes also become one undoable action.", setup: "Connect your tool", setupHint: "Copy the complete setup and paste it into the matching tool. It contains a private token—do not share it.", copyCodex: "Copy Codex config", copyClaude: "Copy Claude Code command", copied: "Copied. You can paste it now.", rotate: "Replace connection token", rotateConfirm: "This immediately invalidates earlier Codex and Claude Code settings. You will need to copy the setup again. Continue?", tokenChanged: "Connection token replaced. Copy the tool setup again.", recent: "Recent MCP actions", noRecent: "No MCP actions yet", outcomes: { success: "Done", denied: "Denied", error: "Failed" }, port: "Port", applyPort: "Apply", advanced: "Advanced connection settings",
  },
  ja: {
    eyebrow: "外部連携", title: "CodexやClaude CodeからChengJingを操作", summary: "ローカルMCP・初期状態はオフ", description: "MCP対応ツールからノート、ホワイトボード、カンバン、ニューロン、タスクを検索・閲覧し、選択した権限に応じて変更できます。接続はこのPC内だけで、インターネットには公開されません。", enabled: "ローカルMCPを有効化", enabledHint: "ChengJingの実行中だけ接続できます", endpoint: "ローカル接続先", running: "接続可能", stopped: "オフ", failed: "起動できません", access: "アクセス権", recommended: "推奨", modes: { "read-only": ["読み取り専用", "検索と閲覧のみ。変更しません"], ask: ["毎回確認", "書き込み前にChengJingが確認します"], allow: ["書き込みを許可", "トークンを持つツールが直接変更できます"] } as Record<McpAccessMode, [string, string]>, allowConfirm: "「書き込みを許可」は操作ごとに確認しません。接続ツールを信頼し、トークンを安全に保管している場合だけ使用してください。有効にしますか？", safety: "MCPから完全削除はできません。外部からの書き込みも1回の取り消し可能な操作になります。", setup: "ツールを接続", setupHint: "完全な設定をコピーして対象ツールへ貼り付けます。秘密のトークンを含むため共有しないでください。", copyCodex: "Codex設定をコピー", copyClaude: "Claude Codeコマンドをコピー", copied: "コピーしました。そのまま貼り付けられます。", rotate: "接続トークンを変更", rotateConfirm: "以前のCodexとClaude Code設定は直ちに無効になります。設定を再度コピーする必要があります。続行しますか？", tokenChanged: "接続トークンを変更しました。ツール設定をもう一度コピーしてください。", recent: "最近のMCP操作", noRecent: "操作履歴はありません", outcomes: { success: "完了", denied: "拒否", error: "失敗" }, port: "ポート", applyPort: "適用", advanced: "接続の詳細設定",
  },
  ko: {
    eyebrow: "외부 연동", title: "Codex와 Claude Code로 ChengJing 제어", summary: "로컬 MCP · 기본값 꺼짐", description: "MCP 호환 도구가 노트, 화이트보드, 칸반, 뉴런 및 할 일을 검색하고 읽으며 선택한 권한에 따라 수정할 수 있습니다. 연결은 이 컴퓨터 안에서만 작동하며 인터넷에 공개되지 않습니다.", enabled: "로컬 MCP 사용", enabledHint: "ChengJing이 실행 중일 때만 연결됩니다", endpoint: "로컬 연결 주소", running: "연결 가능", stopped: "꺼짐", failed: "시작할 수 없음", access: "접근 수준", recommended: "권장", modes: { "read-only": ["읽기 전용", "검색과 읽기만 가능하며 수정하지 않음"], ask: ["매번 확인", "쓰기 전에 ChengJing이 사용자에게 확인"], allow: ["쓰기 허용", "토큰을 가진 도구가 직접 수정 가능"] } as Record<McpAccessMode, [string, string]>, allowConfirm: "쓰기 허용은 작업마다 묻지 않습니다. 연결된 도구를 신뢰하고 토큰을 안전하게 보관한 경우에만 사용하세요. 활성화할까요?", safety: "MCP는 영구 삭제를 제공하지 않습니다. 외부 쓰기도 한 번에 실행 취소할 수 있는 작업이 됩니다.", setup: "도구 연결", setupHint: "전체 설정을 복사해 해당 도구에 붙여넣으세요. 비공개 토큰이 포함되어 있으니 공유하지 마세요.", copyCodex: "Codex 설정 복사", copyClaude: "Claude Code 명령 복사", copied: "복사했습니다. 바로 붙여넣을 수 있습니다.", rotate: "연결 토큰 변경", rotateConfirm: "기존 Codex와 Claude Code 설정이 즉시 무효화됩니다. 설정을 다시 복사해야 합니다. 계속할까요?", tokenChanged: "연결 토큰을 변경했습니다. 도구 설정을 다시 복사하세요.", recent: "최근 MCP 작업", noRecent: "아직 작업 기록이 없습니다", outcomes: { success: "완료", denied: "거부됨", error: "실패" }, port: "포트", applyPort: "적용", advanced: "고급 연결 설정",
  },
} as const;

export function getMcpSettingsCopy(language: AppLanguage) { return copy[language] || copy.en; }
