import type { AppLanguage } from "../types";

const copies = {
  "zh-TW": {
    dueDate: "目標期限",
    dueOptional: "目標期限（選填）",
    setDue: "設定期限…",
    changeDue: "修改期限…",
    removeDue: "移除期限",
    dialogEyebrow: "待辦期限",
    dialogTitle: (title: string) => `設定「${title}」的目標期限`,
    saveDue: "儲存期限",
    chooseDate: "選擇日期",
    calendarLabel: "目標日期月曆",
    previousMonth: "上一個月",
    nextMonth: "下一個月",
    clearDate: "清除日期",
    today: "今天",
    tomorrow: "明天",
    inOneWeek: "一週後",
    todayTitle: "今天",
    todayLead: "先把眼前最重要的事情完成",
    todayEmpty: "今天沒有到期事項，可以從未來挑一件提前完成。",
    overdueTitle: "已過期",
    overdueLead: "決定現在完成，或重新安排期限",
    futureTitle: "接下來",
    futureLead: "依日期由近到遠排列",
    noDateTitle: "尚未排期",
    noDateLead: "需要時再放進時間軸",
    completedLead: "已經完成的事情",
    taskCount: (count: number) => `${count} 件`,
    dueToday: "今天到期",
    overdueDays: (days: number) => `已過期 ${days} 天`,
    dueInDays: (days: number) => `還有 ${days} 天`,
    fromNote: "來自筆記",
  },
  "zh-CN": {
    dueDate: "目标期限",
    dueOptional: "目标期限（选填）",
    setDue: "设置期限…",
    changeDue: "修改期限…",
    removeDue: "移除期限",
    dialogEyebrow: "待办期限",
    dialogTitle: (title: string) => `设置“${title}”的目标期限`,
    saveDue: "保存期限",
    chooseDate: "选择日期", calendarLabel: "目标日期日历", previousMonth: "上个月", nextMonth: "下个月", clearDate: "清除日期", today: "今天", tomorrow: "明天", inOneWeek: "一周后", todayTitle: "今天", todayLead: "先完成眼前最重要的事情", todayEmpty: "今天没有到期事项，可以从未来挑一件提前完成。", overdueTitle: "已过期", overdueLead: "决定现在完成，或重新安排期限", futureTitle: "接下来", futureLead: "按日期由近到远排列", noDateTitle: "尚未排期", noDateLead: "需要时再放进时间轴", completedLead: "已经完成的事情", taskCount: (count: number) => `${count} 件`, dueToday: "今天到期", overdueDays: (days: number) => `已过期 ${days} 天`, dueInDays: (days: number) => `还有 ${days} 天`, fromNote: "来自笔记",
  },
  en: {
    dueDate: "Target date",
    dueOptional: "Target date (optional)",
    setDue: "Set target date…",
    changeDue: "Change target date…",
    removeDue: "Remove target date",
    dialogEyebrow: "Task deadline",
    dialogTitle: (title: string) => `Set a target date for “${title}”`,
    saveDue: "Save target date",
    chooseDate: "Choose date", calendarLabel: "Target date calendar", previousMonth: "Previous month", nextMonth: "Next month", clearDate: "Clear date", today: "Today", tomorrow: "Tomorrow", inOneWeek: "In one week", todayTitle: "Today", todayLead: "Finish what matters most right now", todayEmpty: "Nothing is due today. You can bring one future task forward.", overdueTitle: "Overdue", overdueLead: "Finish it now or give it a realistic new date", futureTitle: "Coming up", futureLead: "Ordered from the nearest date onward", noDateTitle: "Unscheduled", noDateLead: "Place these on the timeline when ready", completedLead: "Things you have already finished", taskCount: (count: number) => `${count} ${count === 1 ? "task" : "tasks"}`, dueToday: "Due today", overdueDays: (days: number) => `${days} ${days === 1 ? "day" : "days"} overdue`, dueInDays: (days: number) => `In ${days} ${days === 1 ? "day" : "days"}`, fromNote: "From a note",
  },
  ja: {
    dueDate: "目標期限",
    dueOptional: "目標期限（任意）",
    setDue: "期限を設定…",
    changeDue: "期限を変更…",
    removeDue: "期限を削除",
    dialogEyebrow: "タスク期限",
    dialogTitle: (title: string) => `「${title}」の目標期限を設定`,
    saveDue: "期限を保存",
    chooseDate: "日付を選択", calendarLabel: "目標日のカレンダー", previousMonth: "前の月", nextMonth: "次の月", clearDate: "日付を消去", today: "今日", tomorrow: "明日", inOneWeek: "1週間後", todayTitle: "今日", todayLead: "今いちばん大切なことから終える", todayEmpty: "今日が期限のタスクはありません。先の予定を一つ進めてもよさそうです。", overdueTitle: "期限超過", overdueLead: "今終えるか、現実的な期限に決め直す", futureTitle: "これから", futureLead: "近い日付から順に表示", noDateTitle: "未定", noDateLead: "準備ができたら時間軸へ", completedLead: "完了したこと", taskCount: (count: number) => `${count}件`, dueToday: "今日まで", overdueDays: (days: number) => `${days}日超過`, dueInDays: (days: number) => `あと${days}日`, fromNote: "ノートから",
  },
  ko: {
    dueDate: "목표 기한",
    dueOptional: "목표 기한(선택)",
    setDue: "기한 설정…",
    changeDue: "기한 변경…",
    removeDue: "기한 제거",
    dialogEyebrow: "할 일 기한",
    dialogTitle: (title: string) => `‘${title}’의 목표 기한 설정`,
    saveDue: "기한 저장",
    chooseDate: "날짜 선택", calendarLabel: "목표 날짜 달력", previousMonth: "이전 달", nextMonth: "다음 달", clearDate: "날짜 지우기", today: "오늘", tomorrow: "내일", inOneWeek: "일주일 후", todayTitle: "오늘", todayLead: "지금 가장 중요한 일부터 끝내기", todayEmpty: "오늘 마감인 일이 없습니다. 미래 일정 하나를 미리 시작해도 좋습니다.", overdueTitle: "기한 지남", overdueLead: "지금 끝내거나 현실적인 날짜로 다시 정하기", futureTitle: "다가오는 일정", futureLead: "가까운 날짜부터 순서대로 표시", noDateTitle: "미정", noDateLead: "준비되면 시간표에 배치", completedLead: "이미 끝낸 일", taskCount: (count: number) => `${count}개`, dueToday: "오늘 마감", overdueDays: (days: number) => `${days}일 지남`, dueInDays: (days: number) => `${days}일 남음`, fromNote: "노트에서",
  },
} as const;

export function getTaskEnhancementCopy(language: AppLanguage) {
  return copies[language] || copies.en;
}
