import type { AppLanguage } from "../types";

const copies = {
  "zh-TW": {
    nav: "許願池", eyebrow: "澄境共創", title: "許願池", description: "留下你希望澄境實現的功能，也可以回應其他人的想法。",
    privacy: "只送出你的共享名稱與留言內容，不會送出筆記或裝置資訊。這個名稱也會用於共享大腦。", identity: "共享身分", regenerate: "修改共享名稱",
    refresh: "重新整理", close: "關閉許願池", adminLogin: "管理員登入", adminLogout: "登出管理員", admin: "管理員", adminActive: "管理員模式已開啟",
    loginTitle: "管理員登入", loginDescription: "登入後可以用管理員身分回覆，並刪除不適當的內容。", password: "管理密碼", login: "登入", loggingIn: "驗證中",
    placeholder: "你希望澄境下一步加入什麼？可以描述使用情境，讓想法更容易被理解。", submit: "投入許願池", submitting: "正在投入", count: "{count}/800",
    loading: "正在聽大家的願望…", empty: "池面還很安靜", emptyDescription: "留下第一個願望，讓澄境知道下一步可以往哪裡走。", loadMore: "載入更早的願望", loadingMore: "載入中",
    reply: "回覆", replyPlaceholder: "留下回應…", submitReply: "送出回覆", cancelReply: "取消", moreReplies: "查看其他 {count} 則回覆", noMoreReplies: "已顯示全部回覆",
    delete: "刪除", deleteWishConfirm: "確定刪除這則願望與所有回覆？", deleteReplyConfirm: "確定刪除這則回覆？", confirmDelete: "確定刪除",
    posted: "願望已投入池中。", replied: "回覆已送出。", deleted: "內容已刪除。", refreshed: "已讀取最新願望。",
    errors: { offline: "目前連不到許願池，請確認網路後再試。", timeout: "許願池回應較慢，請稍後再試。", "rate-limited": "操作太頻繁，請休息一下再試。", "invalid-admin-password": "管理密碼不正確。", "admin-session-expired": "管理員登入已過期，請重新登入。", "invalid-payload": "內容格式不正確，請檢查後再試。", generic: "許願池暫時沒有完成這次操作。" },
  },
  "zh-CN": {
    nav: "许愿池", eyebrow: "澄境共创", title: "许愿池", description: "留下你希望澄境实现的功能，也可以回应其他人的想法。",
    privacy: "只会发送共享名称和留言内容，不会发送笔记或设备信息。这个名称也用于共享大脑。", identity: "共享身份", regenerate: "修改共享名称",
    refresh: "刷新", close: "关闭许愿池", adminLogin: "管理员登录", adminLogout: "退出管理员", admin: "管理员", adminActive: "管理员模式已开启",
    loginTitle: "管理员登录", loginDescription: "登录后可以用管理员身份回复，并删除不适当的内容。", password: "管理密码", login: "登录", loggingIn: "验证中",
    placeholder: "你希望澄境下一步加入什么？可以描述使用场景，让想法更容易理解。", submit: "投入许愿池", submitting: "正在提交", count: "{count}/800",
    loading: "正在聆听大家的愿望…", empty: "池面还很安静", emptyDescription: "留下第一个愿望，让澄境知道下一步可以往哪里走。", loadMore: "加载更早的愿望", loadingMore: "加载中",
    reply: "回复", replyPlaceholder: "留下回复…", submitReply: "发送回复", cancelReply: "取消", moreReplies: "查看其他 {count} 条回复", noMoreReplies: "已显示全部回复",
    delete: "删除", deleteWishConfirm: "确定删除这条愿望及全部回复？", deleteReplyConfirm: "确定删除这条回复？", confirmDelete: "确定删除",
    posted: "愿望已投入池中。", replied: "回复已发送。", deleted: "内容已删除。", refreshed: "已读取最新愿望。",
    errors: { offline: "目前无法连接许愿池，请检查网络后重试。", timeout: "许愿池响应较慢，请稍后重试。", "rate-limited": "操作太频繁，请稍后再试。", "invalid-admin-password": "管理密码不正确。", "admin-session-expired": "管理员登录已过期，请重新登录。", "invalid-payload": "内容格式不正确，请检查后重试。", generic: "许愿池暂时未能完成此操作。" },
  },
  en: {
    nav: "Wish Pool", eyebrow: "Shape ChengJing", title: "Wish Pool", description: "Suggest what ChengJing should build next, or respond to another person's idea.",
    privacy: "Only your shared name and message are sent. Notes and device details stay private. The same name is used in the shared brain.", identity: "Shared identity", regenerate: "Rename shared identity",
    refresh: "Refresh", close: "Close Wish Pool", adminLogin: "Admin sign in", adminLogout: "Sign out admin", admin: "Admin", adminActive: "Admin mode is active",
    loginTitle: "Admin sign in", loginDescription: "Admins can reply with a verified badge and remove inappropriate content.", password: "Admin password", login: "Sign in", loggingIn: "Checking",
    placeholder: "What should ChengJing add next? Describe the situation so others can understand the idea.", submit: "Add wish", submitting: "Adding", count: "{count}/800",
    loading: "Listening for wishes…", empty: "The pool is still quiet", emptyDescription: "Leave the first wish and help ChengJing choose its next step.", loadMore: "Load earlier wishes", loadingMore: "Loading",
    reply: "Reply", replyPlaceholder: "Write a reply…", submitReply: "Send reply", cancelReply: "Cancel", moreReplies: "Show {count} more replies", noMoreReplies: "All replies are visible",
    delete: "Delete", deleteWishConfirm: "Delete this wish and all replies?", deleteReplyConfirm: "Delete this reply?", confirmDelete: "Delete",
    posted: "Your wish was added.", replied: "Reply sent.", deleted: "Content deleted.", refreshed: "Latest wishes loaded.",
    errors: { offline: "The Wish Pool is offline right now. Check your connection and try again.", timeout: "The Wish Pool is taking too long. Try again shortly.", "rate-limited": "Too many actions. Take a short break and try again.", "invalid-admin-password": "The admin password is incorrect.", "admin-session-expired": "The admin session expired. Sign in again.", "invalid-payload": "Check the message and try again.", generic: "The Wish Pool could not complete that action." },
  },
  ja: {
    nav: "願いの池", eyebrow: "ChengJingを共につくる", title: "願いの池", description: "ChengJingに欲しい機能を残したり、ほかの人の案に返信できます。",
    privacy: "共有名とメッセージだけを送信し、ノートや端末情報は送りません。同じ名前を共有脳でも使います。", identity: "共有アイデンティティ", regenerate: "共有名を変更",
    refresh: "更新", close: "願いの池を閉じる", adminLogin: "管理者ログイン", adminLogout: "管理者ログアウト", admin: "管理者", adminActive: "管理者モード",
    loginTitle: "管理者ログイン", loginDescription: "管理者として返信し、不適切な内容を削除できます。", password: "管理パスワード", login: "ログイン", loggingIn: "確認中",
    placeholder: "ChengJingに次はどんな機能が欲しいですか？利用場面も書くと伝わりやすくなります。", submit: "願いを入れる", submitting: "送信中", count: "{count}/800",
    loading: "みんなの願いを読み込んでいます…", empty: "池はまだ静かです", emptyDescription: "最初の願いを残し、ChengJingの次の一歩を教えてください。", loadMore: "以前の願いを表示", loadingMore: "読み込み中",
    reply: "返信", replyPlaceholder: "返信を書く…", submitReply: "返信を送る", cancelReply: "キャンセル", moreReplies: "ほかの返信 {count} 件を表示", noMoreReplies: "すべての返信を表示中",
    delete: "削除", deleteWishConfirm: "この願いとすべての返信を削除しますか？", deleteReplyConfirm: "この返信を削除しますか？", confirmDelete: "削除する",
    posted: "願いを池に入れました。", replied: "返信を送信しました。", deleted: "内容を削除しました。", refreshed: "最新の願いを読み込みました。",
    errors: { offline: "願いの池に接続できません。ネットワークを確認してください。", timeout: "応答に時間がかかっています。後でもう一度お試しください。", "rate-limited": "操作が多すぎます。少し待ってからお試しください。", "invalid-admin-password": "管理パスワードが正しくありません。", "admin-session-expired": "管理者ログインの期限が切れました。", "invalid-payload": "内容を確認してもう一度お試しください。", generic: "この操作を完了できませんでした。" },
  },
  ko: {
    nav: "소원 연못", eyebrow: "함께 만드는 ChengJing", title: "소원 연못", description: "ChengJing에 바라는 기능을 남기거나 다른 사람의 아이디어에 답글을 달 수 있습니다.",
    privacy: "공유 이름과 메시지만 전송하며 노트와 기기 정보는 보내지 않습니다. 같은 이름을 공유 브레인에서도 사용합니다.", identity: "공유 정체성", regenerate: "공유 이름 변경",
    refresh: "새로고침", close: "소원 연못 닫기", adminLogin: "관리자 로그인", adminLogout: "관리자 로그아웃", admin: "관리자", adminActive: "관리자 모드 사용 중",
    loginTitle: "관리자 로그인", loginDescription: "관리자 이름으로 답글을 달고 부적절한 내용을 삭제할 수 있습니다.", password: "관리 비밀번호", login: "로그인", loggingIn: "확인 중",
    placeholder: "ChengJing에 어떤 기능이 추가되면 좋을까요? 사용 상황도 함께 적어 주세요.", submit: "소원 남기기", submitting: "전송 중", count: "{count}/800",
    loading: "모두의 소원을 불러오는 중…", empty: "연못이 아직 조용합니다", emptyDescription: "첫 소원을 남겨 ChengJing의 다음 방향을 알려 주세요.", loadMore: "이전 소원 더 보기", loadingMore: "불러오는 중",
    reply: "답글", replyPlaceholder: "답글 남기기…", submitReply: "답글 보내기", cancelReply: "취소", moreReplies: "다른 답글 {count}개 보기", noMoreReplies: "모든 답글을 표시했습니다",
    delete: "삭제", deleteWishConfirm: "이 소원과 모든 답글을 삭제할까요?", deleteReplyConfirm: "이 답글을 삭제할까요?", confirmDelete: "삭제하기",
    posted: "소원을 남겼습니다.", replied: "답글을 보냈습니다.", deleted: "내용을 삭제했습니다.", refreshed: "최신 소원을 불러왔습니다.",
    errors: { offline: "소원 연못에 연결할 수 없습니다. 네트워크를 확인하세요.", timeout: "응답이 늦어지고 있습니다. 잠시 후 다시 시도하세요.", "rate-limited": "요청이 너무 많습니다. 잠시 쉬었다가 다시 시도하세요.", "invalid-admin-password": "관리 비밀번호가 올바르지 않습니다.", "admin-session-expired": "관리자 로그인이 만료되었습니다.", "invalid-payload": "내용을 확인한 뒤 다시 시도하세요.", generic: "이 작업을 완료하지 못했습니다." },
  },
} as const;

export function getWishPoolCopy(language: AppLanguage) { return copies[language] || copies.en; }
